
name: Adam
hparams:
  lr: 0.0005
  weight_decay: 0.0001
  betas:
    - 0.9
    - 0.999
  eps: 1e-08

lr_scheduler:
  name: linear
  T_max: 100
  eta_min: 0.0
  last_epoch: -1

epochs: 2
batch_size: 516
grad_clip_val: 5.0
num_workers: 6
loss_fn: mae

patience: 10
monitor: val_loss