
name: Adam
hparams:
  lr: 0.00001
  weight_decay: 0.0001
  betas:
    - 0.9
    - 0.999
  eps: 1e-08

lr_scheduler:
  name: linear
  T_max: 100
  eta_min: 0.0
  last_epoch: -1

epochs: 20
batch_size: 2048
grad_clip_val: 1.0
num_workers: 1
loss_fn: mae

patience: 10
monitor: val_loss