
name: s4
hparams:
  hidden_size: 16
  state_size: 16
  n_layers: 2
  # activation: 'elu'
  dropout: 0.2
  # window_size: 12

training_mode: teacher_forcing
parallel_chunking: 1.0
discretization_method: zoh
scan_method: auto

schedule_teacher_forcing:
  # mode: linear
  # start_value: 1.0
  # end_value: 0.0

  # mode: half_half
  # start_value: 1.0
  # end_value: 0.0

  mode: step
  start_value: 1.0
  end_value: 0.0
  step_epoch: 0