
name: s5_no_D
hparams:
  hidden_size: 128
  state_size: 192
  n_layers: 2
  num_blocks: 1 # must divide state_size, number of subblocks in the A matrix
  # activation: 'elu'
  dropout: 0.2
  # window_size: 12

training_mode: teacher_forcing
parallel_chunking: 0.0
discretization_method: zoh
scan_method: auto

schedule_teacher_forcing:
  # mode: linear
  # start_value: 1.0
  # end_value: 0.0

  # mode: half_half
  # start_value: 1.0
  # end_value: 0.0

  # mode: step
  # start_value: 1.0
  # end_value: 0.0
  # step_epoch: 0